// learn-react/src/TODO/Vue/list.vue
<template>
  <div class="list" :class="{done: item.done}">
    <div class="text">{{item.text}}</div>
    <div class="btn success" @click="$emit('done', item.id)">完成</div>
    <div class="btn" @click="$emit('del', item.id)">删除</div>
  </div>
</template>

<script>
export default {
  props: ['item']
}
</script>

// learn-react/src/TODO/React/list.jsx
import React, { Component } from 'react';

class List extends Component {
  render () {
    return (
      <div className={this.props.done ? 'list done' : 'list'}>
        <div className="text">{this.props.text}</div>
        <div
          className="btn success"
          onClick={this.props.doneFn.bind(this.props.app, this.props.id)}
        >完成</div>
        <div
          className="btn"
          onClick={this.props.del.bind(this.props.app, this.props.id)}
        >删除</div>
      </div>
    )
  }
}

export default List
